### ISSUE TITLE
Multi language Support

### ISSUE THREAD

**Issue by BohnSeb** [Rei-x/discord-speech-recognition#22]
If possible it would be great for the speech recognition to be able to accept different languages at the same time

**Comment by Rei-x** [comment]
It's possible, but it would be hard to implement, because speech recognition apis that are used in this library, requires to specify language, **before** sending the request. The most I can do is to give possibility to specify language per user or per guild, for example:
- User A set his language to be deutsch
- User B set his language to be chinese
- User C didn't specify his language, so he will use default guild language, english

All of them can speak in the same channel in the same time and their speech will be recognized correctly.
Will it satisfy your needs?
